#include <iostream>


void printQuadratic1();			// prints 40 prime numbers generated by formula n^2 + n + 41
void printQuadratic2();			// prints 80 prime numbers generated by formula n^2 -79 * n +1601
void isPrime(int n);

int main ()
{

	std::cout << "\n*** Printing 40 primes generated by formula n^2 + n +41 ***\n\n";
	printQuadratic1();

	std::cout << "\n*** Printing 80 primes generated by formula n^2 - 79n + 1601 ***\n\n";
	printQuadratic2();

	isPrime(2);
	isPrime(4);
	isPrime(17);
	isPrime(21);
	isPrime(23);


}

void printQuadratic1()
{
	for (int i = 0; i < 40; ++i)
	{
		//std::cout << i + 1 << ". prime number is = " << (i * i) + i + 41 << std::endl;
		int number = (i * i) + i + 41;
		std::cout << i + 1 << ". ";
		isPrime(number);
	
	}
}

void printQuadratic2()
{
	for (int i = 0; i < 80; ++i)
	{
		//std::cout << i + 1 << ". prime number is = " << (i * i) - (79 * i) + (1601) << std::endl;
		int number = (i * i) - (79 * i) + (1601);
		std::cout << i + 1 << ". ";
		isPrime(number);
	}
}

void isPrime(int n)
{
	int i, m = 0, flag = 0;
	//std::cout << "Enter the Number to check Prime: ";
	//std::cin >> n;
	m = n / 2;
	for (i = 2; i <= m; i++)
	{
		if (n % i == 0)
		{
			std::cout << n << " is not a Prime." << std::endl;
			flag = 1;
			break;
		}
	}
	if (flag == 0)
		std::cout  << "Prime number is = " << n << std::endl;
}
